from pydantic import BaseModel, HttpUrl,Field
from typing import Optional, List
from datetime import datetime
from enum import Enum


#Enums
class JobSource(str,Enum):
    REMOTE_OK = 'remoteok'
    # WE_WORK_REMOTELY = "weworkremotely"
    # LINKEDIN ="linkedin"

class ApplicationStatus(str,Enum):
    DISCOVERED = "discovered" #We just found a job
    MATCHED ="matched"    #AI scored it - it's a good fit
    APPROVED = "approved"  #User said 'Yes to apply'
    APPLIED = "applied"  #Application submitted successfully
    FAILED = "failed" #Something went wrong
    SKIPPED = "skipped" #User said 'No thanks'

#CORE MODELS 

class Job(BaseModel) :
    id:str = Field(...,description="Unique ID for deduplication")
    source :JobSource
    url:HttpUrl
    
    title:str
    company:str
    description:str
    location:str = "Remote"
    salary:Optional[str] = None
    tags:List[str]  = Field(default_factory=list)
    
    posted_date:str
    discovered_at:datetime = Field(default_factory=datetime.now)
    
    
    match_score:Optional[float] = None
    match_reasoning:Optional[str] = None
    status:ApplicationStatus = ApplicationStatus.DISCOVERED
    
    class Config :
        json_encoders = {datetime:lambda v:v.isoformat()}
        
        
class UserProfile(BaseModel):
    """The candidate's information and preferences"""
    name: str
    email: str
    phone: Optional[str] = None
    linkedin: Optional[str] = None
    github: Optional[str] = None
    website: Optional[str] = None
    
    cv_text: str  
    cover_letter_template: str
    
    target_roles: List[str] 
    min_salary: Optional[int] = None
    min_match_score: float = 75.0  # Ignore jobs below this AI score
        

class MatchResult(BaseModel):
    """What my model returns when evaluating the job match"""
    
    match_score:float = Field(...,ge=0,le=100,description="Score from 0 -100")
    reasoning:str = Field(..., description = "Why this score was given")
    key_requirements:List[str]
    missing_skills:List[str]
    
class TailoredContent(BaseModel):
    """Custom CV and cover letter generated by the model"""
    tailored_cv: str
    cover_letter: str
    why_good_fit: List[str]
class TailoredMaterials(BaseModel):
    """Links a job to its custom CV/cover letter"""
    job_id: str
    tailored_cv: str
    tailored_cover_letter: str

###  ApplicationRecord
class ApplicationRecord(BaseModel):
    """A log entry for every application attempt"""
    id: str
    job_id: str
    status: ApplicationStatus
    applied_at: datetime = Field(default_factory=datetime.now)
    error_message: Optional[str] = None
    notes: Optional[str] = None
    
class AgentState(BaseModel):
    """The global context for the agent's workflow """
    
    user_profile:UserProfile
    
    #discovered jobs
    jobs:List[Job] = Field(default_factory=list)

    #results
    applications:List[ApplicationRecord] = Field(default_factory=list)
    
    #stats
    jobs_scrapped_count:int = 0
    jobs_applied_count:int = 0

